Repository Trivivium/devops-2k20, pull requests merged in 2020-03, with the labels that each got.

#41 Update production.yml
  src/production.yml
Labels: web-app

#42 revert using sqlite locally
  src/WebApplication/Startup.cs
Labels: bug

#61 Update dockerpush.yml
  .github/workflows/dockerpush.yml
  .github/workflows/release.yml
Labels: release:minor

#62 Create CONTRIBUTE file
  CONTRIBUTE.md
Labels: norelease

#59 Feature/errors as exceptions
  .gitattributes
  src/WebApplication/Controllers/ApiController.cs
  src/WebApplication/Controllers/TimelineController.cs
  src/WebApplication/Exceptions/UnknownFollowerRelationException.cs
  src/WebApplication/Exceptions/UnknownUserException.cs
  src/WebApplication/ResponseModels/ErrorResponse.cs
  src/WebApplication/Services/TimelineService.cs
  src/WebApplication/Services/UserService.cs
  src/WebApplication/WebApplication.csproj
Labels: release:minor

#65 Added logging
  src/WebApplication/Controllers/ApiController.cs
  src/WebApplication/Controllers/AuthenticationController.cs
  src/WebApplication/Controllers/TimelineController.cs
  src/WebApplication/Extensions/ActionLoggerAttribute.cs
  src/WebApplication/Startup.cs
  src/WebApplication/WebApplication.csproj
Labels: release:major

#69 quick fix
  src/WebApplication/Startup.cs
Labels: release:patch
